service:
  name: y-mobile-slack-app

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  timeout: 30
  environment:
    SENTRY_DSN: ${file(./.env.yml):SENTRY_DSN}

functions:
  notify:
    handler: src/functions/notify.handler
    events:
      - schedule: cron(0 15 * * ? *)
  fetch:
    handler: src/functions/fetch.handler
  generate-chart-url:
    handler: src/functions/generate-chart-url.handler

package:
  exclude:
    - .git/**
    - README.md