service:
  name: y-mobile-slack-app

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  timeout: 30

functions:
  notify:
    handler: src/functions/notify.handler
    events:
      - schedule: cron(0 15 * * ? *)

package:
  exclude:
    - .git/**
    - README.md